bug: inlining a module causes an internal compiler error
bc_inline: function bc/0+4:
  Internal consistency check failed - please report this bug.
  Instruction: {bs_context_to_binary,{literal,<<"hej">>}}
  Error:       {bad_source,{literal,<<"hej">>}}: